### ISSUE TITLE
Tables not being created

### ISSUE THREAD

**Issue by samgranger** [danielgindi/knex-schema-builder#1]
Have tried to get this to work to no avail unfortunately, not sure if this is a bug or if I'm doing something wrong. No tables are being created, except from schema_globals.

My schema.json is as follows:

```
{
    "schema": {
      "posts": {
        "columns": [
          {
            "name": "post",
            "type": "text",
            "nullable": true
          },
          {
            "name": "description",
            "type": "text",
            "nullable": true
          }
        ]
      }
    }
}
```

Hopefully you can see what's going wrong. I really like the idea behind this module.

**Comment by danielgindi** [comment]
Well it _should_ work - it works for me with much huge and complex schemas...
Do you have a `version.json` file?

**Comment by samgranger** [comment]
I have a version.json file, I even copied my schema.json and called it update.2.json - when running, it sets db_version to 2 (obviously after changing version to 2 in version.json) in schema_globals. That's the only part that is working on my side unfortunately.

It might just be me, I just copied the example code you have in the readme and then added a version.json and schema.json. Do I need to have a json with createTable inside of it? A working example would be really nice, I'm assuming that I'm doing something stupid and missed something here.

**Comment by danielgindi** [comment]
I've just tested this with your schema - and it seems fine.
Are you actually calling `install`?

**Comment by samgranger** [comment]
Using this: `schemaInstaller.install(db, schemaPath, function (err) { console.log(err) });`

err seems to be undefined so no hints there.

**Comment by danielgindi** [comment]
Do you want to send a sample project with just the bits that don't work?

**Comment by samgranger** [comment]
Just commited an example where it goes wrong: https://github.com/samgranger/schema_issue

**Comment by danielgindi** [comment]
Alright it's fixed! Just do an `npm update` and it will update

**Comment by samgranger** [comment]
Thanks!
