### ISSUE TITLE
Unexpected token in schema.json is reported as 'empty-database'

### ISSUE THREAD

**Issue by yeya** [danielgindi/knex-schema-builder#9]
When `schema.json` file contains invalid json, the upgrade process ignore the error because `originalVersion === undefined` [here](https://github.com/danielgindi/knex-schema-builder/blob/master/index.js#L591) and throw `empty-database` error instead.

- Steps to reproduce:
Run DB Upgrade with schema.json contains invalid JSON, for example: `{ "schema": "wrong", }`
- Expected Result:
throw `SyntaxError: Unexpected token } in JSON at position X`
- Actual Result:
throw `empty-database`

**Comment by danielgindi** [comment]
Please test with 0.4.5 ;-)

**Comment by yeya** [comment]
index.js:588 ReferenceError: `version is not defined`
